Getting httpd example working.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1244,6 +1244,14 @@ if test -n "$ac_init_help"; then
 
   cat <<\_ACEOF
 
+Optional Packages:
+  --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
+  --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
+  --with-ht=prefix        find headers in prefix/include; library in
+                          prefix/lib
+  --with-lithe=prefix     find headers in prefix/include, library in
+                          prefix/lib
+
 Some influential environment variables:
   CXX         C++ compiler command
   CXXFLAGS    C++ compiler flags
@@ -1679,21 +1687,6 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
-
-#AC_ARG_WITH([boost-headers],
-#  AC_HELP_STRING([--with-boost-headers=DIR],
-#                 [find Boost headers in DIR]),
-#	         [case "$with_boost_headers" in
-#		    yes) AC_MSG_ERROR([
-#*** --with-boost-headers requires an argument]) ;;
-#		    ''|no) AC_MSG_ERROR([
-#*** The Boost headers are REQUIRED and cannot
-#*** be ommited using --without-boost-headers.]) ;;
-#		    *) CPPFLAGS="$CPPFLAGS -I$withval"
-#                       CFLAGS="$CFLAGS -I$withval"
-#                       CXXFLAGS="$CXXFLAGS -I$withval" ;;
-#	          esac],
-#	         [])
 
 # Checks for programs.
 ac_ext=cpp
@@ -2784,6 +2777,284 @@ ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
+# Check for pthread library.
+
+
+{ echo "$as_me:$LINENO: checking for pthread_create in -lpthread" >&5
+echo $ECHO_N "checking for pthread_create in -lpthread... $ECHO_C" >&6; }
+if test "${ac_cv_lib_pthread_pthread_create+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lpthread  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char pthread_create ();
+int
+main ()
+{
+return pthread_create ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_pthread_pthread_create=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_pthread_pthread_create=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_pthread_pthread_create" >&5
+echo "${ECHO_T}$ac_cv_lib_pthread_pthread_create" >&6; }
+if test $ac_cv_lib_pthread_pthread_create = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBPTHREAD 1
+_ACEOF
+
+  LIBS="-lpthread $LIBS"
+
+else
+  { { echo "$as_me:$LINENO: error:
+*** The pthread library is missing or cannot be found.
+See \`config.log' for more details." >&5
+echo "$as_me: error:
+*** The pthread library is missing or cannot be found.
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
+# Check for the ht.
+
+# Check whether --with-ht was given.
+if test "${with_ht+set}" = set; then
+  withval=$with_ht;
+	    case "$with_ht" in
+		 yes) { { echo "$as_me:$LINENO: error:
+*** --with-ht requires an argument" >&5
+echo "$as_me: error:
+*** --with-ht requires an argument" >&2;}
+   { (exit 1); exit 1; }; } ;;
+		 ''|no) { { echo "$as_me:$LINENO: error:
+*** The ht library is REQUIRED and cannot be ommited using --without-ht." >&5
+echo "$as_me: error:
+*** The ht library is REQUIRED and cannot be ommited using --without-ht." >&2;}
+   { (exit 1); exit 1; }; } ;;
+		 *) CFLAGS="$CFLAGS -I$withval/include"
+		    CPPFLAGS="$CPPFLAGS -I$withval/include"
+		    CXXFLAGS="$CXXFLAGS -I$withval/include"
+		    LDFLAGS="$LDFLAGS -L$withval/lib"
+		    LIBS="-lht $LIBS" ;;
+	    esac
+
+fi
+
+
+{ echo "$as_me:$LINENO: checking for ht" >&5
+echo $ECHO_N "checking for ht... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+		#include <ht.h>
+                void entry() { }
+int
+main ()
+{
+ht_request(1);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_HT 1
+_ACEOF
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+		 { { echo "$as_me:$LINENO: error:
+*** The ht library is missing or cannot be found.
+*** Did you try using --with-ht=prefix?
+See \`config.log' for more details." >&5
+echo "$as_me: error:
+*** The ht library is missing or cannot be found.
+*** Did you try using --with-ht=prefix?
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+# Check for the Lithe.
+
+# Check whether --with-lithe was given.
+if test "${with_lithe+set}" = set; then
+  withval=$with_lithe;
+	    case "$with_lithe" in
+		 yes) { { echo "$as_me:$LINENO: error:
+*** --with-lithe requires an argument" >&5
+echo "$as_me: error:
+*** --with-lithe requires an argument" >&2;}
+   { (exit 1); exit 1; }; } ;;
+		 ''|no) { { echo "$as_me:$LINENO: error:
+*** Lithe is REQUIRED and cannot be ommited using --without-lithe." >&5
+echo "$as_me: error:
+*** Lithe is REQUIRED and cannot be ommited using --without-lithe." >&2;}
+   { (exit 1); exit 1; }; } ;;
+		 *) CFLAGS="$CFLAGS -I$withval/include"
+		    CPPFLAGS="$CPPFLAGS -I$withval/include"
+		    CXXFLAGS="$CXXFLAGS -I$withval/include"
+		    LDFLAGS="$LDFLAGS -L$withval/lib"
+		    LIBS="-llithe $LIBS" ;;
+	    esac
+
+fi
+
+
+{ echo "$as_me:$LINENO: checking for lithe" >&5
+echo $ECHO_N "checking for lithe... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+		#include <lithe.h>
+
+int
+main ()
+{
+lithe_sched_request(1);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LITHE 1
+_ACEOF
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+		 { { echo "$as_me:$LINENO: error:
+*** Lithe is missing or cannot be found.
+*** Did you try using --with-lithe=prefix?
+See \`config.log' for more details." >&5
+echo "$as_me: error:
+*** Lithe is missing or cannot be found.
+*** Did you try using --with-lithe=prefix?
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+
+#AC_ARG_WITH([boost-headers],
+#  AC_HELP_STRING([--with-boost-headers=DIR],
+#                 [find Boost headers in DIR]),
+#	         [case "$with_boost_headers" in
+#		    yes) AC_MSG_ERROR([
+#*** --with-boost-headers requires an argument]) ;;
+#		    ''|no) AC_MSG_ERROR([
+#*** The Boost headers are REQUIRED and cannot
+#*** be ommited using --without-boost-headers.]) ;;
+#		    *) CPPFLAGS="$CPPFLAGS -I$withval"
+#                       CFLAGS="$CFLAGS -I$withval"
+#                       CXXFLAGS="$CXXFLAGS -I$withval" ;;
+#	          esac],
+#	         [])
+
 # Look for BOOST_PP.
 #AC_LANG_PUSH([C++])
 #AC_CHECK_HEADERS([boost/preprocessor/library.hpp], [], [AC_MSG_FAILURE([
@@ -2799,7 +3070,6 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 #AC_LANG_POP([C++])
 
 # Checks for header files.
-
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -5335,7 +5605,7 @@ fi
 done
 
 
-ac_config_files="$ac_config_files Makefile"
+ac_config_files="$ac_config_files Makefile examples/Makefile"
 
 ac_aux_dir=
 for ac_dir in "$srcdir" "$srcdir/.." "$srcdir/../.."; do
@@ -5939,6 +6209,7 @@ for ac_config_target in $ac_config_targets
 do
   case $ac_config_target in
     "Makefile") CONFIG_FILES="$CONFIG_FILES Makefile" ;;
+    "examples/Makefile") CONFIG_FILES="$CONFIG_FILES examples/Makefile" ;;
 
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
